version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9293:9293"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
      REMOTE_SERVICE_HOST: "host.docker.internal"
      BULKHEAD: "true"
      WORKERS: 2

volumes:
  gem_cache:
  node_modules: